### ISSUE TITLE
Tiny many things

### ISSUE THREAD

**Issue by gossi** [hokulea/hokulea#191]
- [x] `<IconButton>` to be a `<button>`
- [x] cursor on `<AppHeader>`
- [x] `<AppHeader>` menu to take full width, but contents around ~80% of it
- [x] style `<hr>` for `<Menu>`
- [ ] global `flow` class
- [x] ~make icons `1cap`~
- [x] give listbox overflow styles:
  ```css
  [role="listbox"] {
    overflow: auto;
    overscroll-behavior: contain;
  }
  ```
- [x] check listbox scroll with that (keyboard navigation)
- [x] `(popover)`
  - [x] `opened` and `closed` hooks
  - [x] `open` and `close` actions
